"""
Módulos IA P3-30: Detección de Contenido Generado por IA
Detecta si un video parece haber sido generado completamente por IA.
"""
import re
import logging
from typing import Dict, Optional, Tuple
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class AIDetectionResult:
    """Resultado de detección de contenido IA."""
    is_ai_generated: bool
    confidence: float
    indicators: Dict[str, float]
    recommendation: str


class ContentAIDetector:
    """Detector de contenido generado por IA."""

    AI_PATTERNS = {
        'title_patterns': [
            r'generated by',
            r'created by',
            r'made with',
            r'ai video',
            r'artificial intelligence',
            r'chatgpt video',
            r'midjourney',
            r'dall-e',
            r'stable diffusion',
            r'ia generad[oa]'
        ],
        'description_patterns': [
            r'this video was created using',
            r'powered by',
            r'ai tool',
            r'generated with',
            r'automatically generated',
            r'machine learning'
        ],
        'channel_patterns': [
            'ai video', 'ai generated', 'bot channel',
            'auto video', 'ia creation', 'artificial'
        ]
    }

    TEMPLATE_INDICATORS = [
        'step 1', 'step 2', 'step 3',
        'first,', 'second,', 'third,',
        'here are', 'in this video',
        'today we will', 'in this tutorial',
        'let me show you', 'follow these'
    ]

    UNNATURAL_PATTERNS = [
        r'\.{2,}',
        r'\s{3,}',
        r'[A-Z]{5,}',
        r'\b(giggle|guffaw|snicker)\b',
    ]

    def __init__(self):
        self._detection_count = 0

    def analyze_title(self, title: str) -> float:
        """Analiza el título en busca de indicadores de IA."""
        title_lower = title.lower()
        score = 0.0

        for pattern in self.AI_PATTERNS['title_patterns']:
            if re.search(pattern, title_lower):
                score += 0.3

        if any(word in title_lower for word in ['tutorial', 'guide', 'how to']):
            if not any(word in title_lower for word in ['learn', 'step', 'complete', 'full']):
                score += 0.1

        return min(score, 1.0)

    def analyze_description(self, description: str) -> float:
        """Analiza la descripción en busca de indicadores de IA."""
        desc_lower = description.lower()
        score = 0.0

        for pattern in self.AI_PATTERNS['description_patterns']:
            if re.search(pattern, desc_lower):
                score += 0.3

        template_count = sum(1 for t in self.TEMPLATE_INDICATORS if t in desc_lower)
        if template_count >= 3:
            score += 0.2
        elif template_count >= 5:
            score += 0.4

        return min(score, 1.0)

    def analyze_channel(self, channel_name: str, channel_description: str = "") -> float:
        """Analiza el canal en busca de indicadores de IA."""
        name_lower = channel_name.lower()
        desc_lower = channel_description.lower()
        combined = f"{name_lower} {desc_lower}"
        score = 0.0

        for pattern in self.AI_PATTERNS['channel_patterns']:
            if pattern in combined:
                score += 0.4

        return min(score, 1.0)

    def analyze_video_metadata(
        self,
        title: str,
        description: str = "",
        channel_name: str = "",
        channel_description: str = "",
        tags: list = None
    ) -> AIDetectionResult:
        """
        Analiza metadatos del video para detectar contenido generado por IA.
        Args:
            title: Título del video
            description: Descripción del video
            channel_name: Nombre del canal
            channel_description: Descripción del canal
            tags: Lista de tags del video
        Returns:
            AIDetectionResult con análisis
        """
        self._detection_count += 1

        title_score = self.analyze_title(title)
        desc_score = self.analyze_description(description)
        channel_score = self.analyze_channel(channel_name, channel_description)

        tags_score = 0.0
        if tags:
            tags_text = ' '.join(str(t).lower() for t in tags)
            if any(pattern in tags_text for pattern in ['ai-generated', 'ai-art', 'ai-video']):
                tags_score = 0.5

        weights = {'title': 0.4, 'description': 0.3, 'channel': 0.2, 'tags': 0.1}
        final_score = (
            title_score * weights['title'] +
            desc_score * weights['description'] +
            channel_score * weights['channel'] +
            tags_score * weights['tags']
        )

        is_ai = final_score > 0.4

        if final_score > 0.7:
            recommendation = "Alta probabilidad de contenido generado por IA - verificar manualmente"
        elif final_score > 0.4:
            recommendation = "Probable contenido generado por IA - revisar descripciones"
        elif final_score > 0.2:
            recommendation = "Contenido mixto o parcialmente asistido por IA"
        else:
            recommendation = "Probablemente contenido original/humano"

        result = AIDetectionResult(
            is_ai_generated=is_ai,
            confidence=round(final_score, 2),
            indicators={
                'title_score': round(title_score, 2),
                'description_score': round(desc_score, 2),
                'channel_score': round(channel_score, 2),
                'tags_score': round(tags_score, 2)
            },
            recommendation=recommendation
        )

        if is_ai:
            logger.info(f"Contenido IA detectado en '{title[:30]}...' (confianza: {final_score:.2f})")

        return result

    def analyze_thumbnail_text(self, thumbnail_text: str = "") -> float:
        """Analiza texto detectado en miniatura."""
        if not thumbnail_text:
            return 0.0

        text_lower = thumbnail_text.lower()
        score = 0.0

        if len(thumbnail_text) < 20 and len(thumbnail_text.split()) < 5:
            score += 0.3

        if any(char.isupper() for char in thumbnail_text[1:]):
            score += 0.2

        return min(score, 0.5)

    def get_statistics(self) -> Dict:
        """Retorna estadísticas de detección."""
        return {
            "total_analyzed": self._detection_count,
            "model": "ContentAIDetector v1.0"
        }


def create_ai_detector() -> ContentAIDetector:
    """Crea una instancia del detector de contenido IA."""
    return ContentAIDetector()


_global_detector: Optional[ContentAIDetector] = None


def get_ai_detector() -> ContentAIDetector:
    """Obtiene la instancia global del detector de IA."""
    global _global_detector
    if _global_detector is None:
        _global_detector = create_ai_detector()
    return _global_detector